{"level": "DEBUG", "message": "Debug message", "timestamp": "2024-12-23T20:56:33.308196+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "INFO", "message": "Info message", "timestamp": "2024-12-23T20:56:33.308435+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "WARNING", "message": "Warning message", "timestamp": "2024-12-23T20:56:33.308492+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "ERROR", "message": "Error message", "timestamp": "2024-12-23T20:56:33.308549+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "Critical message", "timestamp": "2024-12-23T20:56:33.308587+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "Exception message", "timestamp": "2024-12-23T20:56:33.308624+00:00", "logger": "my_app", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/Users/math/Documents/Workspace/Python/logging_example/main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero"}
